INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('TL', 'JCTL', 'Jim Carrey Towing Ltd :: Towing and Labour Vendor', 'jctl@vendor.com', '92933929', 8.7, 50.00, 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('TL', 'MTTL', 'Mike Tyson Towing Ltd :: Towing and Labour Vendor', 'mttl@vendor.com', '92933930', 8.8, 55.00,  'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('TL', 'DJTL', 'Dwayne Johnson Towing Ltd :: Towing and Labour Vendor', 'djtl@vendor.com', '92933931', 9.7, 52.00,  'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('SS', 'CBSS', 'Christian Bale Salvage Shop Ltd :: Salvage Shop Vendor', 'cbss@vendor.com', '92933932', 5.7, 56.00, 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('SS', 'BASS', 'Ben Affleck Salvage Shop Ltd :: Salvage Shop Vendor','bass@vendor.com', '92933933', 8.2, 54.00,  'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('SS', 'PSS', 'Pattinson Salvage Shop Ltd :: Salvage Shop Vendor','pss@vendor.com', '92933934', 8.4, 60.00,  'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('GR', 'CEGR', 'Chris Evans Glass Repair Ltd :: Glass Repair Vendor', 'cegr@vendor.com', '92933935', 7.6, 51.00, 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('GR', 'CHGR', 'Chris Hemsworth Glass Repair Ltd :: Glass Repair Vendor', 'chgr@vendor.com', '92933936', 7.7, 59.00, 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_CD(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('GR', 'BCGR', 'Bryan Cranston Glass Repair Ltd :: Glass Repair Vendor', 'bcgr@vendor.com', '92933937', 9.1, 56.00, 'admin', 'admin');
