INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    1, 9,  TO_DATE('05/02/22', 'DD/MM/RR'), 5000.00, 'FS', 'Check', 'Paid', 'brn9482053012', 'acc947283910', 'NA','admin', 'admin'); 
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    2, 10,  TO_DATE('05/02/22', 'DD/MM/RR'), 5500.00, 'FS', 'Credit Card', 'Paid', 'brn2947104829', 'acc284739102', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    3, 6,  TO_DATE('05/06/22', 'DD/MM/RR'), 3000.00, 'FS', 'Check', 'Paid', 'brn3847105938', 'acc938402751', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    4, 14,  TO_DATE('15/11/22', 'DD/MM/RR'), 1000.00, 'PS', 'Check', 'Paid', 'brn2749182841', 'acc485739201', 'NA','admin', 'admin'); 
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS, PREVIOUS_CLAIM_ID,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    5, 6,  TO_DATE('26/05/23', 'DD/MM/RR'), 5000.00, 'FS', 'Cash', 'Paid', '3', 'brn5782039471', 'acc495028374', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS, PREVIOUS_CLAIM_ID,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    6, 10,  TO_DATE('05/06/23', 'DD/MM/RR'), 3000.00, 'FS', 'Check', 'Paid', '2', 'brn3940283759', 'acc203948475', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS, PREVIOUS_CLAIM_ID,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    7, 10,  TO_DATE('05/07/23', 'DD/MM/RR'), 1400.00, 'FS', 'Check', 'Paid', '6', 'brn1029384756', 'acc183945702', 'NA','admin', 'admin'); 
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    8, 15,  TO_DATE('18/07/23', 'DD/MM/RR'), 1000.00, 'PS', 'Bank Transfer', 'Paid', 'brn2039485764', 'acc384720594', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    9, 12,  TO_DATE('07/11/23', 'DD/MM/RR'), 1000.00, 'FS', 'Bank Transfer', 'Paid', 'brn3850203948', 'acc583920102', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    10, 18,  TO_DATE('28/11/23', 'DD/MM/RR'), 3000.00, 'FS', 'Cash', 'Paid', 'brn4958302941', 'acc203948576', 'NA','admin', 'admin'); 
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    11, 7,  TO_DATE('26/11/23', 'DD/MM/RR'), 2000.00, 'FS', 'Check', 'Paid', 'brn5839201045', 'acc194857203', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    12, 17,  TO_DATE('24/12/23', 'DD/MM/RR'), 4000.00, 'FS', 'Check', 'Paid', 'brn1039485203', 'acc385729104', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    13, 16,  TO_DATE('05/01/24', 'DD/MM/RR'), 6000.00, 'FS', 'Check', 'Paid', 'brn2948502739', 'acc294857302', 'NA','admin', 'admin'); 
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    14, 2,  TO_DATE('10/02/24', 'DD/MM/RR'), 2000.00, 'FS', 'Check', 'Paid', 'brn5830294815', 'acc583920104', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    16, 3,  TO_DATE('20/02/24', 'DD/MM/RR'), 1000.00, 'PS', 'Check', 'Paid', 'brn4857293841', 'acc394720584', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    19, 8,  TO_DATE('08/05/24', 'DD/MM/RR'), 3000.00, 'FS', 'Credit Card', 'Paid', 'brn5947203849', 'acc293847501', 'NA','admin', 'admin'); 
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    22, 13,  TO_DATE('25/07/24', 'DD/MM/RR'), 1000.00, 'FS', 'Check', 'Paid', 'brn3948751029', 'acc193847502', 'NA','admin', 'admin');
    
INSERT INTO SYSTEM.PAYMENT (CLAIM_ID, CLAIM_CONTACT_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_TYPE_CODE, PAYMENT_METHOD, PAYMENT_STATUS,
    PAYMENT_REFERENCE_NUMBER, BANK_ACCOUNT_NUMBER, PAYMENT_NOTE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    24, 11,  TO_DATE('15/08/24', 'DD/MM/RR'), 500.00, 'FS', 'Cash', 'Paid', 'brn1039475823', 'acc485720394', 'NA','admin', 'admin');
    
