INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('TL', 'JCTL', 'Jim Carrey Towing Ltd :: Towing and Labour Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('TL', 'MTTL', 'Mike Tyson Towing Ltd :: Towing and Labour Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('TL', 'DJTL', 'Dwayne Johnson Towing Ltd :: Towing and Labour Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('SS', 'CBSS', 'Christian Bale Salvage Shop Ltd :: Salvage Shop Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('SS', 'BASS', 'Ben Affleck Salvage Shop Ltd :: Salvage Shop Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('SS', 'PSS', 'Pattinson Salvage Shop Ltd :: Salvage Shop Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('GR', 'CEGR', 'Chris Evans Glass Repair Ltd :: Glass Repair Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('GR', 'CHGR', 'Chris Hemsworth Glass Repair Ltd :: Glass Repair Vendor', 'admin', 'admin');

INSERT INTO SYSTEM.VENDOR_AVAILABLE_LIST(VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_FULL_NAME, CREATED_USER_ID, UPDATED_USER_ID)
VALUES ('GR', 'BCGR', 'Bryan Cranston Glass Repair Ltd :: Glass Repair Vendor', 'admin', 'admin');
