INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'9', '9', 'CN00001', TO_DATE('02/02/2022', 'DD/MM/RR'), TO_DATE('02/02/2022', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with a car', 'Online',
'CL', 'CR', 'N', 'Y', 'None', 5000.00, 5500.00, 5000.00, TO_DATE('05/02/2022', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'10', '10', 'CN00002', TO_DATE('03/02/2022', 'DD/MM/RR'), TO_DATE('03/02/2022', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with a car', 'Online',
'CL', 'CR', 'N', 'Y', 'None', 5500.00, 5500.00, 5500.00, TO_DATE('05/02/2022', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'6', '6', 'CN00003', TO_DATE('03/06/2022', 'DD/MM/RR'), TO_DATE('03/06/2022', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with an animal', 'Online',
'CH', 'AN', 'N', 'Y', 'None', 3000.00, 3000.00, 3000.00, TO_DATE('05/06/2022', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'14', '14', 'CN00004', TO_DATE('11/11/2022', 'DD/MM/RR'), TO_DATE('11/11/2022', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with animal', 'Online',
'CH', 'AN', 'N', 'Y', 'None', 1000.00, 1500.00, 1000.00, TO_DATE('15/11/2022', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'6', '6', 'CN00005', TO_DATE('25/05/2023', 'DD/MM/RR'), TO_DATE('25/05/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Natural disaster; vehicle damaged in storm', 'Online',
'CH', 'ND', 'N', 'Y', 'None', 5000.00, 6000.00, 5000.00, TO_DATE('26/05/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'10', '10', 'CN00006', TO_DATE('02/06/2023', 'DD/MM/RR'), TO_DATE('02/06/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with a truck', 'Online',
'CL', 'CR', 'N', 'Y', 'None', 3000.00, 3500.00, 3000.00, TO_DATE('05/06/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'10', '10', 'CN00007', TO_DATE('02/07/2023', 'DD/MM/RR'), TO_DATE('02/07/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Car fire', 'Online',
'CH', 'FR', 'N', 'Y', 'None', 1400.00, 1500.00, 1400.00, TO_DATE('05/07/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'15', '15', 'CN00008', TO_DATE('17/07/2023', 'DD/MM/RR'), TO_DATE('17/07/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Car part theft - tyres', 'Online',
'CH', 'TH', 'N', 'Y', 'None', 1000.00, 1500.00, 1000.00, TO_DATE('18/07/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'12', '12', 'CN00009', TO_DATE('02/11/2023', 'DD/MM/RR'), TO_DATE('02/11/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Car fire', 'Online',
'CH', 'FR', 'N', 'Y', 'None', 1000.00, 1500.00, 1000.00, TO_DATE('07/11/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'18', '18', 'CN00010', TO_DATE('24/11/2023', 'DD/MM/RR'), TO_DATE('24/11/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Car fire', 'Online',
'CH', 'FR', 'N', 'Y', 'None', 3000.00, 3500.00, 3000.00, TO_DATE('28/11/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'7', '7', 'CN00011', TO_DATE('25/11/2023', 'DD/MM/RR'), TO_DATE('25/11/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with a truck', 'Online',
'CL', 'CR', 'N', 'Y', 'None', 2000.00, 3500.00, 2000.00, TO_DATE('26/11/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'17', '17', 'CN00012', TO_DATE('15/12/2023', 'DD/MM/RR'), TO_DATE('15/12/2023', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with truck', 'Online',
'CL', 'CR', 'N', 'Y', 'None', 4000.00, 4500.00, 4000.00, TO_DATE('24/12/2023', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'16', '16', 'CN00013', TO_DATE('02/01/2024', 'DD/MM/RR'), TO_DATE('02/01/2024', 'DD/MM/RR'), 'Auto', 'Closed', 'Car fire', 'Online',
'CH', 'FR', 'N', 'Y', 'None', 6000.00, 6500.00, 6000.00, TO_DATE('05/01/2024', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'2', '2', 'CN00014', TO_DATE('06/02/2024', 'DD/MM/RR'), TO_DATE('06/02/2024', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with a car', 'Online',
'CL', 'CR', 'N', 'Y', 'None', 2000.00, 2000.00, 2000.00, TO_DATE('10/02/2024', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'4', '4', 'CN00015', TO_DATE('13/02/2024', 'DD/MM/RR'), TO_DATE('13/02/2024', 'DD/MM/RR'), 'Auto', 'Rejected', 'Collision with a car while reversing', 'Online',
'CL', 'CR', 'Y', 'Y', 'None', 1000.00, 1500.00, 'Claim is rejected; policy expiry; validated by policy investigator', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'3', '3', 'CN00016', TO_DATE('15/02/2024', 'DD/MM/RR'), TO_DATE('14/02/2024', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with a tree while reversing', 'Online',
'CL', 'OB', 'Y', 'Y', 'None', 1000.00, 1500.00, 1000.00, TO_DATE('20/02/2024', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'7', '7', 'CN00017', TO_DATE('02/04/2024', 'DD/MM/RR'), TO_DATE('02/04/2024', 'DD/MM/RR'), 'Auto', 'Validating', 'Collision with an animal', 'Online',
'CH', 'AN', 'N', 'Y', 'None', 2000.00, 3500.00, 'Claim and Policy validation in progress', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'5', '5', 'CN00018', TO_DATE('03/05/2024', 'DD/MM/RR'), TO_DATE('03/05/2024', 'DD/MM/RR'), 'Auto', 'Rejected', 'Collision with an animal', 'Online',
'CH', 'AN', 'N', 'Y', 'None', 3000.00, 3000.00, 'Claim is rejected; false claim; validated by auditor', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'8', '8', 'CN00019', TO_DATE('06/05/2024', 'DD/MM/RR'), TO_DATE('06/05/2024', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with a truck', 'Online',
'CL', 'CR', 'N', 'Y', 'None', 3000.00, 3500.00, 3000.00, TO_DATE('08/05/2024', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'16', '16', 'CN00020', TO_DATE('12/07/2024', 'DD/MM/RR'), TO_DATE('12/07/2024', 'DD/MM/RR'), 'Auto', 'Rejected', 'Windsheild damage', 'Online',
'CH', 'GL', 'N', 'Y', 'None', 3500.00, 3500.00, 'Claim is rejected; false claim; validated by auditor', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'14', '14', 'CN00021', TO_DATE('13/07/2024', 'DD/MM/RR'), TO_DATE('13/07/2024', 'DD/MM/RR'), 'Auto', 'Rejected', 'Car fire', 'Online',
'CH', 'FR', 'N', 'Y', 'None', 500.00, 1500.00, 'Claim is rejected; policy expiry; validated by policy investigator', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'13', '13', 'CN00022', TO_DATE('23/07/2024', 'DD/MM/RR'), TO_DATE('23/07/2024', 'DD/MM/RR'), 'Auto', 'Closed', 'Collision with car', 'Online',
'CL', 'CR', 'Y', 'Y', 'None', 1000.00, 1500.00, 1000.00, TO_DATE('25/07/2024', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'9', '9', 'CN00023', TO_DATE('11/08/2024', 'DD/MM/RR'), TO_DATE('11/08/2024', 'DD/MM/RR'), 'Auto', 'Rejected', 'Collision with animal', 'Online',
'CH', 'AN', 'N', 'Y', 'None', 2000.00, 3000.00, 'Claim is rejected; policy expiry; validated by policy investigator', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, PAYMENT_AMOUNT, PAYMENT_DATE, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'11', '11', 'CN00024', TO_DATE('14/08/2024', 'DD/MM/RR'), TO_DATE('14/08/2024', 'DD/MM/RR'), 'Auto', 'Closed', 'Windsheid damage', 'Online',
'CH', 'GL', 'N', 'Y', 'None', 500.00, 1500.00, 500.00, TO_DATE('15/08/2024', 'DD/MM/RR'), 'Claim is valid', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'18', '18', 'CN00025', TO_DATE('04/09/2024', 'DD/MM/RR'), TO_DATE('04/09/2024', 'DD/MM/RR'), 'Auto', 'Rejected', 'Collision with tree while reversing', 'Online',
'CL', 'OB', 'N', 'Y', 'None', 5400.00, 5500.00, 'Claim is rejected; false claim; validated by auditor', 'admin', 'admin');

INSERT INTO SYSTEM.CLAIM(CLAIM_CONTACT_ID, POLICY_ID, CLAIM_NUMBER, CLAIM_DATE, ACTUAL_LOSS_DATE, CLAIM_TYPE, CLAIM_STATUS, CLAIM_DESCRIPTION,
CLAIM_REPORTED_CHANNEL, COVERAGE_CODE, SUB_COVERAGE_CODE, SELF_FAULT_INDICATOR, CLAIM_CONTACT_ALIVE_FLAG, LEGAL_STATUS, CLAIM_AMOUNT,
CLAIM_RESERVE_AMOUNT, CLAIM_VALIDATION_NOTES, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
'19', '19', 'CN00026', TO_DATE('10/09/2024', 'DD/MM/RR'), TO_DATE('10/09/2024', 'DD/MM/RR'), 'Auto', 'Rejected', 'Car fire', 'Online',
'CH', 'FR', 'N', 'Y', 'None', 5000.00, 5500.00, 'Claim is rejected; policy expiry; validated by policy investigator', 'admin', 'admin');


--as the CLAIMS are created, we have to update the claim count of the clients in policy_holder table. We are using directly policy_holder_id 
--instead of join with auto_policy table as for our case, policy_holder_id will be equal to policy_id and has one-to-one relationship

UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 2;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 3;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 4;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 5;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 2 WHERE POLICY_HOLDER_ID = 6;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 2 WHERE POLICY_HOLDER_ID = 7;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 8;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 2 WHERE POLICY_HOLDER_ID = 9;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 3 WHERE POLICY_HOLDER_ID = 10;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 11;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 12;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 13;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 2 WHERE POLICY_HOLDER_ID = 14;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 15;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 2 WHERE POLICY_HOLDER_ID = 16;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 17;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 2 WHERE POLICY_HOLDER_ID = 18;
UPDATE SYSTEM.POLICY_HOLDER SET TOTAL_CLAIM_COUNT = 1 WHERE POLICY_HOLDER_ID = 19;
