INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (1, 9, 'ICD25', 'Minor', 800.00 , 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (1, 9, 'ICD11' , 'Major', 1400.00 ,'Completed', 'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (2, 10, 'ICD18', 'Minor', 600.00 , 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (2, 10,'ICD27', 'Major', 1600.00 , 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (3, 6,'ICD13', 'Minor', 500.00, 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (4, 14, 'ICD14', 'Minor', 300.00 , 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (6, 10, 'ICD19', 'Moderate', 400.00 , 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (6, 10, 'ICD25', 'Major', 1000.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (11, 7, 'ICD13', 'Minor', 150.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (12, 17,'ICD11', 'Major', 1500.00, 'Completed' ,'admin', 'admin');

INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (12, 17,'ICD12', 'Minor', 550.00, 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (14, 2, 'ICD28', 'Major', 1000.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (15, 4, 'ICD24', 'Minor', 300.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (16, 3, 'ICD24', 'Minor', 100.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (17, 7, 'ICD25', 'Minor', 400.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (18, 5,'ICD20', 'Moderate', 1000.00, 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (19, 8, 'ICD24', 'Minor', 500.00 , 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (20, 16,'ICD02', 'Critical', 1500.00, 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (20, 16,'ICD10', 'Major', 600.00, 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (20, 16,'ICD23', 'Minor', 100.00, 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (22, 13,'ICD22', 'Minor', 300.00, 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (22, 13,'ICD14', 'Minor', 100.00 , 'Completed' ,'admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (23, 9, 'ICD09', 'Minor', 100.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (23, 9, 'ICD08', 'Major', 800.00, 'Completed','admin', 'admin');
    
INSERT INTO SYSTEM.INJURY (CLAIM_ID, CLAIM_CONTACT_ID, INJURY_CODE, INJURY_SEVERITY, MED_EXPENSES, 
    ONGOING_TREATMENT_INDICATOR, CREATED_USER_ID, UPDATED_USER_ID) 
    VALUES (24, 11, 'ICD14', 'Minor', 100.00, 'Completed','admin', 'admin');
