INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    1, 9, 'TL', 'MTTL','mttl@vendor.com', '92933929', 8.7, 50.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    2, 10, 'TL', 'JCTL','jctl@vendor.com', '92933930', 9.0, 40.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    3, 6, 'TL', 'DJTL','djtl@vendor.com', '92933931', 8.5, 45.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    4, 14, 'TL', 'MTTL','mttl1@vendor.com', '92933929', 8.7, 50.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    5, 6, 'SS', 'BASS','bass@vendor.com', '92933932', 8.9, 57.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    6, 10, 'TL', 'MTTL','mttl2@vendor.com', '92933929', 8.7, 50.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    7, 10, 'TL', 'JCTL','jctl1@vendor.com', '92933930', 9.0, 40.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    9, 12, 'TL', 'DJTL','djtl1@vendor.com', '92933931', 8.5, 45.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    10, 18, 'TL', 'JCTL','jctl2@vendor.com', '92933930', 9.0, 40.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    11, 7, 'TL', 'MTTL','mttl3@vendor.com', '92933929', 8.7, 50.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    12, 17, 'TL', 'JCTL','jctl3@vendor.com', '92933930', 9.0, 40.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    13, 16, 'TL', 'DJTL','djtl2@vendor.com', '92933931', 8.5, 45.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    14, 2, 'TL', 'DJTL','djtl3@vendor.com', '92933931', 8.5, 45.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    16, 3, 'TL', 'MTTL','mttl4@vendor.com', '92933929', 8.7, 50.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    17, 7, 'TL', 'MTTL','mttl5@vendor.com', '92933929', 8.7, 50.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    19, 8, 'TL', 'JCTL','jctl4@vendor.com', '92933930', 9.0, 40.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    22, 13, 'TL', 'JCTL','jctl5@vendor.com', '92933930', 9.0, 40.00, 'admin', 'admin');
    
INSERT INTO SYSTEM.VENDOR (CLAIM_ID, CLAIM_CONTACT_ID, VENDOR_TYPE_CODE, VENDOR_NAME_CODE, VENDOR_EMAIL, VENDOR_PHONE, VENDOR_RATING,
    SERVICE_RATE, CREATED_USER_ID, UPDATED_USER_ID) VALUES(
    24, 11, 'GR', 'BCGR','bcgr@vendor.com', '92933935', 8.3, 55.00, 'admin', 'admin');
