INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    1, '00001', 10000.00, 10000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Credit Card', 'NA', 'admin', 'admin');

INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    2, '00002', 10000.00, 8000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Monthly', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    3, '00003',10000.00, 9000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Debit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    4, '00004',10000.00, 10000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/24', 'DD/MM/RR'), 'Y', 'Expired', 
    TO_DATE('02/01/24', 'DD/MM/RR'), 'Annually', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    5, '00005',10000.00, 10000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Cancelled', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Credit Card', 'Not needed anymore', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    6, '00006',10000.00, 2000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Quarterly', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    7, '00007', 10000.00, 8000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Quarterly', 'Debit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    8, '00008',10000.00, 7000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Debit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    9, '00009',10000.00, 5000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/24', 'DD/MM/RR'), 'Y', 'Expired', 
    TO_DATE('02/01/24', 'DD/MM/RR'), 'Annually', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    10, '00010',10000.00, 100.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Cancelled', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Credit Card', 'Not needed anymore', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    11, '00011',10000.00, 9500.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    12, '00012', 10000.00, 9000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Monthly', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    13, '00013',10000.00, 9000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Debit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    14, '00014',10000.00, 9000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/24', 'DD/MM/RR'), 'Y', 'Expired', 
    TO_DATE('02/01/24', 'DD/MM/RR'), 'Annually', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    15, '00015',10000.00, 9000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Cancelled', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Credit Card', 'Not needed anymore', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    16, '00016',10000.00, 4000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Quarterly', 'Credit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    17, '00017', 10000.00, 6000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Quarterly', 'Debit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    18, '00018',10000.00, 7000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/25', 'DD/MM/RR'), 'N', 'Active', 
    TO_DATE('02/01/25', 'DD/MM/RR'), 'Annually', 'Debit Card', 'NA', 'admin', 'admin');
    
INSERT INTO SYSTEM.AUTO_POLICY(POLICY_HOLDER_ID,POLICY_NUMBER,TOTAL_COVERAGE_LIMIT,AMOUNT_DEDUCTIBLE,TOTAL_PREMIUM_AMOUNT,POLICY_START_DATE,
    POLICY_EXPIRY_DATE,POLICY_EXPIRED_FLAG,POLICY_STATUS,POLICY_RENEWAL_DATE,PAYMENT_TYPE,PAYMENT_METHOD,CANCELLATION_REASON,
    CREATED_USER_ID,UPDATED_USER_ID)
    VALUES(
    19, '00019',10000.00, 10000.00, 250000.00, TO_DATE('01/01/15', 'DD/MM/RR'), TO_DATE('03/01/24', 'DD/MM/RR'), 'Y', 'Expired', 
    TO_DATE('02/01/24', 'DD/MM/RR'), 'Annually', 'Credit Card', 'NA', 'admin', 'admin');
    
